version: "3.3"
services:
  php:
    build: 
      context: ./php
    volumes:
      - ..:/var/www/html
    ports:
      - "9000:9000"
  nginx:
    build: 
      context: ./nginx
    volumes:
      - ..:/var/www/html
    ports:
      - "80:80"
      - "443:443"